[package]
name = "order_management"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "order_management"
path = "order_management.rs"

[dependencies]
deribit-base = { workspace = true }
deribit-fix = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }