[package]
name = "market_data"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "market_data_streaming"
path = "market_data_streaming.rs"

[dependencies]
deribit-base = { workspace = true }
deribit-fix = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }