[package]
name = "basic"
version = "0.1.0"
edition = "2024"

[dependencies]
deribit-base = { workspace = true }
deribit-fix = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
